@startuml Notifications BC Aggregate

package "Notifications Aggregate" {
  abstract class Notifications <<AggregateRoot>> {
    - id: NotificationId
    - message: NotificationMessage
    - date: NotificationDate
    - recipients: List<UserId>
    --
    + send(): void
  }

  class InAppNotification <<Entity>> extends Notifications
  class EmailNotification <<Entity>> extends Notifications {
    - email: EmailAddress
  }
  class SMSNotification <<Entity>> extends Notifications {
    - phoneNumber: PhoneNumber
  }

  class NotificationId <<ValueObject>> {
    - value: Long
  }

  class NotificationMessage <<ValueObject>> {
    - text: String
  }

  class NotificationDate <<ValueObject>> {
    - value: LocalDateTime
  }

  class UserId <<ValueObject>> {
    - value: Long
  }

  class EmailAddress <<ValueObject>> {
    - value: String
  }

  class PhoneNumber <<ValueObject>> {
    - value: String
  }

  Notifications *-- NotificationId
  Notifications *-- NotificationMessage
  Notifications *-- NotificationDate
  Notifications *-- "*" UserId
  EmailNotification *-- EmailAddress
  SMSNotification *-- PhoneNumber
}

@enduml
