@startuml RegistroUsuario
actor Usuario

Usuario -> User : new(username, password, email)
activate User
User -> UserId : generate()
UserId --> User : id
User -> EncryptedPassword : hash(password)
EncryptedPassword --> User : hashedPassword
deactivate User

Usuario -> Authenticator : setStrategy(LocalAuthenticator)
User -> Authenticator : authenticate(username, password)
Authenticator --> User : boolean

User -> Notifications : send()
activate Notifications
Notifications -> NotificationFactory : createNotification()
NotificationFactory -> EmailNotification : send(message)
EmailNotification --> NotificationFactory : enviado
Notifications --> User : email enviado
deactivate Notifications

Usuario -> Email : abrir y confirmar link
activate User
User -> User : verifyEmail()
User --> Usuario : cuenta activada
deactivate User
@enduml
